apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: server
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.server.pdb.minAvailable }}
  selector:
    matchLabels:
      app: server
