{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: server
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: server
  endpoints:
    - port: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: worker
  endpoints:
    - port: metrics
{{- end }}
